/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee.core.views;

import java.awt.Color;
import javax.swing.JOptionPane;
import packagee.core.controllers.utils.ControllerContainer;
import packagee.core.controllers.utils.Response;
import packagee.core.controllers.utils.Status;

public class AdminView extends javax.swing.JFrame {

    // ── CAMPOS PRIVADOS ───────────────────────────────────────────────
    private int x, y;
    private final ControllerContainer controllers;

    // ── CONSTRUCTOR ───────────────────────────────────────────────────
    public AdminView(ControllerContainer controllers) {
        initComponents();
        this.controllers = controllers;
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        // Día 4-5: cargar ComboBoxes automáticamente al abrir
        loadDoctorComboBox();
        loadPatientComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new packagee.core.models.PanelRound();
        panelup = new packagee.core.models.PanelRound();
        btnClose = new javax.swing.JButton();
        txtAdminView = new javax.swing.JLabel();
        bgPanel = new packagee.core.models.PanelRound();
        btnDoctorView = new javax.swing.JButton();
        btnPatientView = new javax.swing.JButton();
        txtFirstname = new javax.swing.JLabel();
        fieldFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JLabel();
        fielLastname = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        txtSpecialty = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JLabel();
        fielLicenseNumber = new javax.swing.JTextField();
        txtAssignedOffice = new javax.swing.JLabel();
        fieldAssignedOffice = new javax.swing.JTextField();
        txtUser = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JTextField();
        txtPsswordConfirmation = new javax.swing.JLabel();
        fieldPasswordConfirmation = new javax.swing.JTextField();
        cboxSpecialty = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        SeparatorRight = new javax.swing.JSeparator();
        CboxDoctor = new javax.swing.JComboBox<>();
        txtDoctor = new javax.swing.JLabel();
        txtPatient = new javax.swing.JLabel();
        cboxPatient = new javax.swing.JComboBox<>();
        SeparatorLeft = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Background.setRadius(50);

        panelup.setRadius(50);
        panelup.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelupMouseDragged(evt);
            }
        });
        panelup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelupMousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtAdminView.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtAdminView.setText("ADMIN VIEW");

        javax.swing.GroupLayout panelupLayout = new javax.swing.GroupLayout(panelup);
        panelup.setLayout(panelupLayout);
        panelupLayout.setHorizontalGroup(
            panelupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelupLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtAdminView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        panelupLayout.setVerticalGroup(
            panelupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAdminView))
        );

        btnDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnDoctorView.setText("DOCTOR VIEW");
        btnDoctorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorViewActionPerformed(evt);
            }
        });

        btnPatientView.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnPatientView.setText("PATIENT VIEW");
        btnPatientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientViewActionPerformed(evt);
            }
        });

        txtFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtFirstname.setText("Firstname");

        fieldFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLastname.setText("Lastname");

        fielLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtID.setText("ID");

        fieldID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtSpecialty.setText("Specialty");

        txtLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLicenseNumber.setText("License Number");

        fielLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAssignedOffice.setText("Assigned office");

        fieldAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUser.setText("User");

        fieldUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPassword.setText("Password");

        fieldPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPsswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPsswordConfirmation.setText("Password confirmation");

        fieldPasswordConfirmation.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cboxSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        SeparatorRight.setOrientation(javax.swing.SwingConstants.VERTICAL);

        CboxDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CboxDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDoctor.setText("Doctor");

        txtPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPatient.setText("Patient");

        cboxPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        SeparatorLeft.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(326, 326, 326)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstname)
                                    .addComponent(txtSpecialty))
                                .addGap(18, 18, 18)
                                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgPanelLayout.createSequentialGroup()
                                        .addComponent(cboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtLicenseNumber)
                                        .addGap(18, 18, 18)
                                        .addComponent(fielLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgPanelLayout.createSequentialGroup()
                                        .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtLastname)
                                        .addGap(18, 18, 18)
                                        .addComponent(fielLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtID)
                                        .addGap(18, 18, 18)
                                        .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addComponent(txtAssignedOffice)
                                .addGap(18, 18, 18)
                                .addComponent(fieldAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(bgPanelLayout.createSequentialGroup()
                                    .addComponent(txtUser)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgPanelLayout.createSequentialGroup()
                                    .addComponent(txtPassword)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgPanelLayout.createSequentialGroup()
                                    .addComponent(txtPsswordConfirmation)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDoctorView)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(CboxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(txtDoctor)))
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)
                        .addGap(318, 318, 318)))
                .addComponent(SeparatorRight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPatientView)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(cboxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txtPatient)))
                .addGap(88, 88, 88))
            .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                    .addContainerGap(707, Short.MAX_VALUE)
                    .addComponent(SeparatorLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(523, 523, 523)))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addComponent(SeparatorRight)
                .addContainerGap())
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname)
                    .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastname)
                    .addComponent(fielLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpecialty)
                    .addComponent(cboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLicenseNumber)
                    .addComponent(fielLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAssignedOffice)
                    .addComponent(fieldAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser)
                            .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPsswordConfirmation)
                            .addComponent(fieldPasswordConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(txtDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(CboxDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(btnDoctorView)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(123, 123, 123)
                .addComponent(btnLogout)
                .addGap(38, 38, 38))
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(txtPatient)
                .addGap(18, 18, 18)
                .addComponent(cboxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnPatientView)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SeparatorLeft)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addComponent(panelup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelupMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelupMousePressed

    private void panelupMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelupMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelupMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String id = fieldID.getText();
        String first = fieldFirstname.getText();
        String last = fielLastname.getText();           // fielLastname (sin 'd')
        String spec = cboxSpecialty.getItemAt(cboxSpecialty.getSelectedIndex());
        String license = fielLicenseNumber.getText();     // fielLicenseNumber (sin 'd')
        String office = fieldAssignedOffice.getText();
        String username = fieldUser.getText();
        String password = fieldPassword.getText();
        String confirm = fieldPasswordConfirmation.getText();

        Response response = controllers.getDoctorController().registerDoctor(
                id, username, first, last,
                password, confirm,
                spec, license, office
        );

        if (response.getStatus() == Status.CREATED || response.getStatus() == Status.OK) {
            showMessage("Doctor registered successfully!", true);
            clearDoctorFields();
            loadDoctorComboBox(); // actualizar ComboBox tras agregar
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDoctorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorViewActionPerformed
        String selected = CboxDoctor.getItemAt(CboxDoctor.getSelectedIndex());
        if (selected == null || selected.equals("Select one")) {
            showMessage("Please select a doctor.", false);
            return;
        }

        try {
            long doctorId = Long.parseLong(selected);
            this.setVisible(false);
            // isFromAdmin = true → btnBack activo en DoctorView
            new DoctorView(controllers, doctorId, true).setVisible(true);
        } catch (NumberFormatException e) {
            showMessage("Invalid doctor selection.", false);
        }
    }//GEN-LAST:event_btnDoctorViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        this.setVisible(false);
        new LoginView(controllers).setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPatientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientViewActionPerformed
        String selected = cboxPatient.getItemAt(cboxPatient.getSelectedIndex());
        if (selected == null || selected.equals("Select one")) {
            showMessage("Please select a patient.", false);
            return;
        }

        try {
            long patientId = Long.parseLong(selected);
            this.setVisible(false);
            // isFromAdmin = true → btnBack activo en PatientView
            new PatientView(controllers, patientId, true).setVisible(true);
        } catch (NumberFormatException e) {
            showMessage("Invalid patient selection.", false);
        }
    }//GEN-LAST:event_btnPatientViewActionPerformed
    private void loadDoctorComboBox() {
        CboxDoctor.removeAllItems();
        CboxDoctor.addItem("Select one");
        Response response = controllers.getDoctorController().getAllDoctors();
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("doctors");
            if (list instanceof java.util.ArrayList) {
                for (Object obj : (java.util.ArrayList<?>) list) {
                    if (obj instanceof java.util.HashMap) {
                        java.util.HashMap<?, ?> d = (java.util.HashMap<?, ?>) obj;
                        CboxDoctor.addItem(d.get("id") + " - " + d.get("firstname") + " " + d.get("lastname"));
                    }
                }
            }
        }
    }

    private void loadPatientComboBox() {
        cboxPatient.removeAllItems();
        cboxPatient.addItem("Select one");
        Response response = controllers.getPatientController().getAllPatients();
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("patients");
            if (list instanceof java.util.ArrayList) {
                for (Object obj : (java.util.ArrayList<?>) list) {
                    if (obj instanceof java.util.HashMap) {
                        java.util.HashMap<?, ?> p = (java.util.HashMap<?, ?>) obj;
                        cboxPatient.addItem(p.get("id") + " - " + p.get("firstname") + " " + p.get("lastname"));
                    }
                }
            }
        }
    }

    // ── HELPERS ───────────────────────────────────────────────────────
    private void showMessage(String message, boolean success) {
        int type = success ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(this, message, success ? "Success" : "Error", type);
    }

    private void clearDoctorFields() {
        fieldFirstname.setText("");
        fielLastname.setText("");
        fieldID.setText("");
        fielLicenseNumber.setText("");
        fieldAssignedOffice.setText("");
        fieldUser.setText("");
        fieldPassword.setText("");
        fieldPasswordConfirmation.setText("");
        cboxSpecialty.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private packagee.core.models.PanelRound Background;
    private javax.swing.JComboBox<String> CboxDoctor;
    private javax.swing.JSeparator SeparatorLeft;
    private javax.swing.JSeparator SeparatorRight;
    private packagee.core.models.PanelRound bgPanel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDoctorView;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPatientView;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboxPatient;
    private javax.swing.JComboBox<String> cboxSpecialty;
    private javax.swing.JTextField fielLastname;
    private javax.swing.JTextField fielLicenseNumber;
    private javax.swing.JTextField fieldAssignedOffice;
    private javax.swing.JTextField fieldFirstname;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldPasswordConfirmation;
    private javax.swing.JTextField fieldUser;
    private packagee.core.models.PanelRound panelup;
    private javax.swing.JLabel txtAdminView;
    private javax.swing.JLabel txtAssignedOffice;
    private javax.swing.JLabel txtDoctor;
    private javax.swing.JLabel txtFirstname;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtLastname;
    private javax.swing.JLabel txtLicenseNumber;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtPatient;
    private javax.swing.JLabel txtPsswordConfirmation;
    private javax.swing.JLabel txtSpecialty;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
