/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee.core.views;
 import packagee.core.controllers.utils.NavigationController;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import packagee.core.controllers.utils.ControllerContainer;
import packagee.core.controllers.utils.Response;
import packagee.core.controllers.utils.Status;
import packagee.core.models.Appointment;
import packagee.core.models.Hospitalization;
import packagee.core.models.User;
 
public class DoctorView extends javax.swing.JFrame {
 
    // ── CAMPOS PRIVADOS ───────────────────────────────────────────────
    private int x, y;
    private final ControllerContainer controllers;
    private final long doctorId;
    private final boolean isFromAdmin;
    private NavigationController navigationController;
 
    // ── CONSTRUCTOR DESDE LOGIN DIRECTO ───────────────────────────────
    public DoctorView(ControllerContainer controllers, long doctorId) {
        this(controllers, doctorId, false);
    }
 
    // ── CONSTRUCTOR DESDE ADMINVIEW (Back habilitado) ─────────────────
    public DoctorView(ControllerContainer controllers, long doctorId, boolean isFromAdmin) {
        initComponents();
        this.controllers  = controllers;
        this.doctorId     = doctorId;
        this.isFromAdmin  = isFromAdmin;
 
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        this.navigationController =
        new NavigationController(controllers);
 
        // Día 4-5: btnBack visible SOLO para admin
        btnBack.setVisible(isFromAdmin);
 
        // Día 4-5: cargar datos del doctor logueado en los campos
        loadDoctorData();
 
        // Día 4-5: cargar ComboBoxes automáticamente
        loadPatientComboBoxes();
        loadAppointmentComboBoxes();
        loadHospitalizationComboBox();
    }

    public DoctorView(ControllerContainer controllers) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public DoctorView(ControllerContainer controllers, User user) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public DoctorView(User user, User temp, ArrayList<User> users, ArrayList<Hospitalization> hospitalizations, ArrayList<Appointment> appointments) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyAppmentPanel = new packagee.core.models.PanelRound();
        panelUp = new packagee.core.models.PanelRound();
        btnClose = new javax.swing.JButton();
        txtDoctorView = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        TpaneDoctorView = new javax.swing.JTabbedPane();
        background = new javax.swing.JPanel();
        rbtnTotalAppments = new javax.swing.JRadioButton();
        ScrollAppmentVisual = new javax.swing.JScrollPane();
        AppmentVisual = new javax.swing.JTable();
        RbtnPendingAppments = new javax.swing.JRadioButton();
        btnLogout = new javax.swing.JButton();
        bgAppment = new javax.swing.JPanel();
        cboxPatient = new javax.swing.JComboBox<>();
        txtPatient = new javax.swing.JLabel();
        ScrollHistoryAppment = new javax.swing.JScrollPane();
        AppmentHistory = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        bgModifyInfo = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JLabel();
        fielFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JLabel();
        fieldLastname = new javax.swing.JTextField();
        txtSpecialty = new javax.swing.JLabel();
        txtLicenseNumber = new javax.swing.JLabel();
        fieldLicenseNumber = new javax.swing.JTextField();
        txtAssignedOffice = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        txtUser = new javax.swing.JLabel();
        fieldAssignedOffice = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        txtPassword = new javax.swing.JLabel();
        txtPasswordConfirm = new javax.swing.JLabel();
        fieldPasswordConfirm = new javax.swing.JTextField();
        cboxSpecialty = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        backgroundRquest = new javax.swing.JPanel();
        txtAppmentID = new javax.swing.JLabel();
        txtmedicalAppment = new javax.swing.JLabel();
        cboxAppmentID = new javax.swing.JComboBox<>();
        Separatorleft = new javax.swing.JSeparator();
        btnAccept = new javax.swing.JButton();
        txtReschedule = new javax.swing.JLabel();
        txtApmment = new javax.swing.JLabel();
        cboxAppment = new javax.swing.JComboBox<>();
        btnAcceptReschedule = new javax.swing.JButton();
        txtNewtimeAppment = new javax.swing.JLabel();
        fieldNewtimeappment = new javax.swing.JTextField();
        txtReasonAppment = new javax.swing.JLabel();
        fieldReasonAppment = new javax.swing.JTextField();
        SeparatorCenter = new javax.swing.JSeparator();
        txtCompleteMedicalAppment = new javax.swing.JLabel();
        txtAppmentComplete = new javax.swing.JLabel();
        cboxAppmentComplete = new javax.swing.JComboBox<>();
        txtDiagnosis = new javax.swing.JLabel();
        txtObservations = new javax.swing.JLabel();
        txtRcommendedtreatment = new javax.swing.JLabel();
        txtIndication = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        txtHospitalization = new javax.swing.JLabel();
        txtHospitalReason = new javax.swing.JLabel();
        txtEntry = new javax.swing.JLabel();
        fieldEntry = new javax.swing.JTextField();
        txtDuration = new javax.swing.JLabel();
        fieldDuration = new javax.swing.JTextField();
        txtObservationsHospital = new javax.swing.JLabel();
        ScrollObservationsHospital = new javax.swing.JScrollPane();
        AtxtObservationsHospital = new javax.swing.JTextArea();
        btnGenerate = new javax.swing.JButton();
        xboxRequest = new javax.swing.JComboBox<>();
        rbtnRequest = new javax.swing.JRadioButton();
        rbtnPatientID = new javax.swing.JRadioButton();
        ScrollDiagnosis = new javax.swing.JScrollPane();
        AtxtDiagnosis = new javax.swing.JTextArea();
        ScrollObservations = new javax.swing.JScrollPane();
        AtxtObservations = new javax.swing.JTextArea();
        ScrollTreatment = new javax.swing.JScrollPane();
        atxtTreatmennt = new javax.swing.JTextArea();
        ScrollIndication = new javax.swing.JScrollPane();
        AtxtIndication = new javax.swing.JTextArea();
        SeparatorRight = new javax.swing.JSeparator();
        btnCancel = new javax.swing.JButton();
        cboxPatientID = new javax.swing.JComboBox<>();
        ScrollReason = new javax.swing.JScrollPane();
        atxtReason = new javax.swing.JTextArea();
        bgMedications = new javax.swing.JPanel();
        appmentID = new javax.swing.JLabel();
        txtmedicationName = new javax.swing.JLabel();
        txtMedicationName = new javax.swing.JTextField();
        txtDose = new javax.swing.JLabel();
        fieldDose = new javax.swing.JTextField();
        txtadminroute = new javax.swing.JLabel();
        fieldadminroute = new javax.swing.JTextField();
        txtFrecuency = new javax.swing.JLabel();
        fieldFrecuency = new javax.swing.JTextField();
        txtTrmentDuration = new javax.swing.JLabel();
        fieldTreatmentDuration = new javax.swing.JTextField();
        txtAddInstructions = new javax.swing.JLabel();
        fieldAddInstructions = new javax.swing.JTextField();
        ScrollMedications = new javax.swing.JScrollPane();
        prescribeMedicationsTable = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnPrescribe = new javax.swing.JButton();
        cbappmentIDmedications = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        historyAppmentPanel.setRadius(50);

        panelUp.setRadius(50);
        panelUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelUpMouseDragged(evt);
            }
        });
        panelUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelUpMousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtDoctorView.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDoctorView.setText("DOCTOR VIEW");

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpLayout = new javax.swing.GroupLayout(panelUp);
        panelUp.setLayout(panelUpLayout);
        panelUpLayout.setHorizontalGroup(
            panelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDoctorView)
                .addGap(32, 32, 32)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        panelUpLayout.setVerticalGroup(
            panelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtDoctorView, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBack))
        );

        rbtnTotalAppments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbtnTotalAppments.setText("Total appointments");
        rbtnTotalAppments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTotalAppmentsActionPerformed(evt);
            }
        });

        AppmentVisual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Patient", "Specialty", "Type", "Status"
            }
        ));
        ScrollAppmentVisual.setViewportView(AppmentVisual);

        RbtnPendingAppments.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RbtnPendingAppments.setText("Pending appointments");
        RbtnPendingAppments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnPendingAppmentsActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogout)
                    .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(rbtnTotalAppments)
                            .addGap(18, 18, 18)
                            .addComponent(RbtnPendingAppments))
                        .addGroup(backgroundLayout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(ScrollAppmentVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTotalAppments)
                    .addComponent(RbtnPendingAppments))
                .addGap(18, 18, 18)
                .addComponent(ScrollAppmentVisual, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(23, 23, 23))
        );

        TpaneDoctorView.addTab("Appointments visualization", background);

        cboxPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxPatient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtPatient.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPatient.setText("Patient");

        AppmentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollHistoryAppment.setViewportView(AppmentHistory);

        btnSearch.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgAppmentLayout = new javax.swing.GroupLayout(bgAppment);
        bgAppment.setLayout(bgAppmentLayout);
        bgAppmentLayout.setHorizontalGroup(
            bgAppmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAppmentLayout.createSequentialGroup()
                .addGroup(bgAppmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgAppmentLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(txtPatient)
                        .addGap(18, 18, 18)
                        .addComponent(cboxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgAppmentLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(ScrollHistoryAppment, javax.swing.GroupLayout.PREFERRED_SIZE, 1133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgAppmentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(601, 601, 601))
        );
        bgAppmentLayout.setVerticalGroup(
            bgAppmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgAppmentLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bgAppmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPatient)
                    .addComponent(cboxPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ScrollHistoryAppment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnSearch)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        TpaneDoctorView.addTab("History Appointments of a patient", bgAppment);

        txtFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtFirstname.setText("Firstname");

        fielFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLastname.setText("Lastname");

        fieldLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtSpecialty.setText("Specialty");

        txtLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLicenseNumber.setText("License Number");

        fieldLicenseNumber.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAssignedOffice.setText("Assigned office");

        fieldUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUser.setText("User");

        fieldAssignedOffice.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        fieldPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPassword.setText("Password");

        txtPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPasswordConfirm.setText("Password confirmation");

        fieldPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        cboxSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "General Medicine", "Cardiology", "Pediatrics", "Neurology", "Traumatology & Orthopedics", "Gynecology & Obstetrics", "Dermatology", "Psychiatry", "Oncology", "Ophthalmology", "Internal Medicine" }));

        btnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgModifyInfoLayout = new javax.swing.GroupLayout(bgModifyInfo);
        bgModifyInfo.setLayout(bgModifyInfoLayout);
        bgModifyInfoLayout.setHorizontalGroup(
            bgModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgModifyInfoLayout.createSequentialGroup()
                .addGroup(bgModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgModifyInfoLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(txtFirstname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fielFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtLastname)
                        .addGap(18, 18, 18)
                        .addComponent(fieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtSpecialty)
                        .addGap(18, 18, 18)
                        .addComponent(cboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgModifyInfoLayout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(txtLicenseNumber)
                        .addGap(18, 18, 18)
                        .addComponent(fieldLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAssignedOffice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgModifyInfoLayout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addGroup(bgModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldUser, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(bgModifyInfoLayout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(txtPasswordConfirm))
                    .addGroup(bgModifyInfoLayout.createSequentialGroup()
                        .addGap(576, 576, 576)
                        .addComponent(btnSave))
                    .addGroup(bgModifyInfoLayout.createSequentialGroup()
                        .addGap(561, 561, 561)
                        .addComponent(fieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        bgModifyInfoLayout.setVerticalGroup(
            bgModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgModifyInfoLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(bgModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname)
                    .addComponent(fielFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastname)
                    .addComponent(fieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSpecialty)
                    .addComponent(cboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgModifyInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLicenseNumber)
                    .addComponent(fieldLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAssignedOffice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAssignedOffice))
                .addGap(30, 30, 30)
                .addComponent(txtUser)
                .addGap(18, 18, 18)
                .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword)
                .addGap(27, 27, 27)
                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordConfirm)
                .addGap(18, 18, 18)
                .addComponent(fieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSave)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        TpaneDoctorView.addTab("Modify info", bgModifyInfo);

        txtAppmentID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAppmentID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAppmentID.setText("Appointment ID");

        txtmedicalAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtmedicalAppment.setText("Accept medical appointment");

        cboxAppmentID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxAppmentID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        Separatorleft.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnAccept.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        txtReschedule.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtReschedule.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReschedule.setText("Reschedule medical appointment");

        txtApmment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtApmment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtApmment.setText("Appointment");

        cboxAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxAppment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        btnAcceptReschedule.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAcceptReschedule.setText("Accept");
        btnAcceptReschedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptRescheduleActionPerformed(evt);
            }
        });

        txtNewtimeAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtNewtimeAppment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNewtimeAppment.setText("New time appointment");

        fieldNewtimeappment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtReasonAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtReasonAppment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtReasonAppment.setText("Reason for appointment");

        fieldReasonAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        SeparatorCenter.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtCompleteMedicalAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCompleteMedicalAppment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCompleteMedicalAppment.setText("Complete medical appointment");

        txtAppmentComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAppmentComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAppmentComplete.setText("Appointment");

        cboxAppmentComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxAppmentComplete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtDiagnosis.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDiagnosis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDiagnosis.setText("Diagnosis");

        txtObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtObservations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtObservations.setText("Observations");

        txtRcommendedtreatment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRcommendedtreatment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRcommendedtreatment.setText("Recommended treatment");

        txtIndication.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtIndication.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIndication.setText("Follow-up indication");

        btnComplete.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        txtHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtHospitalization.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHospitalization.setText("Hospitalization");

        txtHospitalReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtHospitalReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHospitalReason.setText("Reason for hospitalization");

        txtEntry.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtEntry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEntry.setText("Date of entry");

        fieldEntry.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDuration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDuration.setText("Estimated duration");

        fieldDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtObservationsHospital.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtObservationsHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtObservationsHospital.setText("Observations");

        AtxtObservationsHospital.setColumns(20);
        AtxtObservationsHospital.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtObservationsHospital.setRows(5);
        ScrollObservationsHospital.setViewportView(AtxtObservationsHospital);

        btnGenerate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        xboxRequest.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        xboxRequest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        rbtnRequest.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbtnRequest.setText("Requests");

        rbtnPatientID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbtnPatientID.setText("Patient ID");

        AtxtDiagnosis.setColumns(20);
        AtxtDiagnosis.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtDiagnosis.setRows(5);
        ScrollDiagnosis.setViewportView(AtxtDiagnosis);

        AtxtObservations.setColumns(20);
        AtxtObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtObservations.setRows(5);
        ScrollObservations.setViewportView(AtxtObservations);

        atxtTreatmennt.setColumns(20);
        atxtTreatmennt.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        atxtTreatmennt.setRows(5);
        ScrollTreatment.setViewportView(atxtTreatmennt);

        AtxtIndication.setColumns(20);
        AtxtIndication.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtIndication.setRows(5);
        ScrollIndication.setViewportView(AtxtIndication);

        SeparatorRight.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        cboxPatientID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxPatientID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        atxtReason.setColumns(20);
        atxtReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        atxtReason.setRows(5);
        ScrollReason.setViewportView(atxtReason);

        javax.swing.GroupLayout backgroundRquestLayout = new javax.swing.GroupLayout(backgroundRquest);
        backgroundRquest.setLayout(backgroundRquestLayout);
        backgroundRquestLayout.setHorizontalGroup(
            backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundRquestLayout.createSequentialGroup()
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                                        .addComponent(btnAccept)
                                        .addGap(87, 87, 87))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                                        .addComponent(cboxAppmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(67, 67, 67))))
                            .addComponent(txtAppmentID, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Separatorleft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtmedicalAppment)
                        .addGap(22, 22, 22)))
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtReschedule, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtApmment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNewtimeAppment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtReasonAppment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(backgroundRquestLayout.createSequentialGroup()
                            .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundRquestLayout.createSequentialGroup()
                                    .addGap(90, 90, 90)
                                    .addComponent(cboxAppment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backgroundRquestLayout.createSequentialGroup()
                                    .addGap(99, 99, 99)
                                    .addComponent(fieldNewtimeappment, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backgroundRquestLayout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(fieldReasonAppment, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backgroundRquestLayout.createSequentialGroup()
                                    .addGap(112, 112, 112)
                                    .addComponent(btnAcceptReschedule)))
                            .addGap(91, 91, 91))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SeparatorCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnComplete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtAppmentComplete, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCompleteMedicalAppment, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                                        .addGap(99, 99, 99)
                                        .addComponent(cboxAppmentComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 115, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiagnosis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtIndication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtRcommendedtreatment, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(ScrollDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(ScrollObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(ScrollTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(ScrollIndication, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(SeparatorRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHospitalization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtEntry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDuration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtObservationsHospital, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGenerate))
                            .addComponent(ScrollObservationsHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(xboxRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(rbtnRequest)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                                .addComponent(rbtnPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                                .addComponent(cboxPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))))
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHospitalReason, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRquestLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ScrollReason, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))))
        );
        backgroundRquestLayout.setVerticalGroup(
            backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separatorleft)
            .addGroup(backgroundRquestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeparatorCenter)
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtCompleteMedicalAppment)
                        .addGap(10, 10, 10)
                        .addComponent(txtAppmentComplete)
                        .addGap(18, 18, 18)
                        .addComponent(cboxAppmentComplete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiagnosis)
                        .addGap(18, 18, 18)
                        .addComponent(ScrollDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtObservations)
                        .addGap(18, 18, 18)
                        .addComponent(ScrollObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRcommendedtreatment)
                        .addGap(18, 18, 18)
                        .addComponent(ScrollTreatment, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIndication)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollIndication, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComplete)
                        .addGap(12, 12, 12))
                    .addGroup(backgroundRquestLayout.createSequentialGroup()
                        .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtmedicalAppment)
                                .addGap(18, 18, 18)
                                .addComponent(txtAppmentID)
                                .addGap(18, 18, 18)
                                .addComponent(cboxAppmentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btnAccept))
                            .addGroup(backgroundRquestLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(txtReschedule)
                                .addGap(18, 18, 18)
                                .addComponent(txtApmment)
                                .addGap(18, 18, 18)
                                .addComponent(cboxAppment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtNewtimeAppment)
                                .addGap(18, 18, 18)
                                .addComponent(fieldNewtimeappment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtReasonAppment)
                                .addGap(18, 18, 18)
                                .addComponent(fieldReasonAppment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnAcceptReschedule)))
                        .addGap(18, 318, Short.MAX_VALUE))))
            .addGroup(backgroundRquestLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtHospitalization)
                .addGap(18, 18, 18)
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnRequest)
                    .addComponent(rbtnPatientID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xboxRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtHospitalReason)
                .addGap(16, 16, 16)
                .addComponent(ScrollReason, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEntry)
                .addGap(18, 18, 18)
                .addComponent(fieldEntry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDuration)
                .addGap(18, 18, 18)
                .addComponent(fieldDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtObservationsHospital)
                .addGap(18, 18, 18)
                .addComponent(ScrollObservationsHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(backgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerate)
                    .addComponent(btnCancel))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(SeparatorRight, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        TpaneDoctorView.addTab("Request/Appointments", backgroundRquest);

        appmentID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        appmentID.setText("Appointment ID");

        txtmedicationName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtmedicationName.setText("Medication name");

        txtMedicationName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtDose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDose.setText("Dose");

        fieldDose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtadminroute.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtadminroute.setText("Administration route");

        fieldadminroute.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtFrecuency.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtFrecuency.setText("Frecuency");

        fieldFrecuency.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtTrmentDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtTrmentDuration.setText("Treatment duration");

        fieldTreatmentDuration.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAddInstructions.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAddInstructions.setText("Additional instructions");

        fieldAddInstructions.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        prescribeMedicationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Appointment ID", "Medication name", "Dose", "Administration route", "Treatment duration", "Additional instructions", "Frecuency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollMedications.setViewportView(prescribeMedicationsTable);

        btnAdd.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPrescribe.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnPrescribe.setText("Prescribe");
        btnPrescribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrescribeActionPerformed(evt);
            }
        });

        cbappmentIDmedications.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cbappmentIDmedications.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        javax.swing.GroupLayout bgMedicationsLayout = new javax.swing.GroupLayout(bgMedications);
        bgMedications.setLayout(bgMedicationsLayout);
        bgMedicationsLayout.setHorizontalGroup(
            bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgMedicationsLayout.createSequentialGroup()
                .addGroup(bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgMedicationsLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScrollMedications, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgMedicationsLayout.createSequentialGroup()
                                .addGroup(bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgMedicationsLayout.createSequentialGroup()
                                        .addComponent(appmentID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbappmentIDmedications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(txtmedicationName))
                                    .addGroup(bgMedicationsLayout.createSequentialGroup()
                                        .addComponent(txtTrmentDuration)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldTreatmentDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(bgMedicationsLayout.createSequentialGroup()
                                        .addComponent(txtAddInstructions)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldAddInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtFrecuency)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldFrecuency, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgMedicationsLayout.createSequentialGroup()
                                        .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDose)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldDose, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtadminroute)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(fieldadminroute, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd))))
                    .addGroup(bgMedicationsLayout.createSequentialGroup()
                        .addGap(583, 583, 583)
                        .addComponent(btnPrescribe)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        bgMedicationsLayout.setVerticalGroup(
            bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgMedicationsLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appmentID)
                    .addComponent(txtmedicationName)
                    .addComponent(txtMedicationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDose)
                    .addComponent(fieldDose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtadminroute)
                    .addComponent(fieldadminroute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd)
                    .addComponent(cbappmentIDmedications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bgMedicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTrmentDuration)
                    .addComponent(fieldTreatmentDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddInstructions)
                    .addComponent(fieldAddInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFrecuency)
                    .addComponent(fieldFrecuency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(ScrollMedications, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnPrescribe)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        TpaneDoctorView.addTab("Prescribe medications", bgMedications);

        javax.swing.GroupLayout historyAppmentPanelLayout = new javax.swing.GroupLayout(historyAppmentPanel);
        historyAppmentPanel.setLayout(historyAppmentPanelLayout);
        historyAppmentPanelLayout.setHorizontalGroup(
            historyAppmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyAppmentPanelLayout.createSequentialGroup()
                .addGroup(historyAppmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TpaneDoctorView))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        historyAppmentPanelLayout.setVerticalGroup(
            historyAppmentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyAppmentPanelLayout.createSequentialGroup()
                .addComponent(panelUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TpaneDoctorView))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historyAppmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(historyAppmentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUpMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelUpMousePressed

    private void panelUpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUpMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelUpMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed
    private void RbtnPendingAppmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnPendingAppmentsActionPerformed
        rbtnTotalAppments.setSelected(false);
 
        // getDoctorAppointments(id, true) = solo pendientes
        Response response = controllers.getAppointmentQueryController()
                .getDoctorAppointments(String.valueOf(doctorId), true);
 
        // Nombre exacto del JFrame: AppmentVisual
        DefaultTableModel model = (DefaultTableModel) AppmentVisual.getModel();
        model.setRowCount(0);
        fillAppointmentTable(model, response);
    }//GEN-LAST:event_RbtnPendingAppmentsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String first    = fielFirstname.getText();    // fielFirstname (sin 'd')
        String last     = fieldLastname.getText();
        String spec     = cboxSpecialty.getItemAt(cboxSpecialty.getSelectedIndex());
        String license  = fieldLicenseNumber.getText();
        String office   = fieldAssignedOffice.getText();
        String username = fieldUser.getText();
        String password = fieldPassword.getText();
        String confirm  = fieldPasswordConfirm.getText();
 
        Response response = controllers.getDoctorController().updateDoctor(
                String.valueOf(doctorId),
                username, first, last,
                password, confirm,
                spec, license, office
        );
 
        if (response.getStatus() == Status.OK) {
            showMessage("Profile updated successfully!", true);
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       this.setVisible(false);
        new LoginView(controllers).setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       this.setVisible(false);
        new AdminView(controllers).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if (rbtnRequest.isSelected()) {
            // Nombre exacto del JFrame: xboxRequest
            String hospId = xboxRequest.getItemAt(xboxRequest.getSelectedIndex());
            if (hospId == null || hospId.equals("Select one")) {
                showMessage("Please select a hospitalization.", false);
                return;
            }
 
            Response response = controllers.getHospitalizationManagementController()
                    .denyHospitalization(hospId);
 
            if (response.getStatus() == Status.OK) {
                showMessage("Hospitalization cancelled.", true);
                loadHospitalizationComboBox();
            } else {
                showMessage(response.getMessage(), false);
            }
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        String patId        = cboxPatientID.getItemAt(cboxPatientID.getSelectedIndex());
        String reason       = atxtReason.getText();
        String observations = AtxtObservationsHospital.getText();
        String entryDate    = fieldEntry.getText();
 
        Response response = controllers.getHospitalizationManagementController()
                .hospitalizeFromAppointment(
                        null,                        // appointmentId (no aplica aquí)
                        patId,
                        String.valueOf(doctorId),
                        entryDate,
                        reason,
                        "IMC",                       // roomType por defecto
                        observations
                );
 
        if (response.getStatus() == Status.OK || response.getStatus() == Status.CREATED) {
            showMessage("Hospitalization generated.", true);
            clearGenerateFields();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
         String patientId = cboxPatient.getItemAt(cboxPatient.getSelectedIndex());
        if (patientId == null || patientId.equals("Select one")) {
            showMessage("Please select a patient.", false);
            return;
        }
 
        Response response = controllers.getAppointmentQueryController()
                .getPatientAppointments(patientId);
 
        // Nombre exacto del JFrame: AppmentHistory
        DefaultTableModel model = (DefaultTableModel) AppmentHistory.getModel();
        model.setRowCount(0);
        fillAppointmentTable(model, response);
 
    } 
    // ── BOTÓN PRESCRIBE: limpiar tabla de medicamentos ────────────────
    //GEN-LAST:event_btnSearchActionPerformed
private void btnPrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribeActionPerformed
        // Nombre exacto del JFrame: prescribeMedicationsTable
        DefaultTableModel model = (DefaultTableModel) prescribeMedicationsTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void rbtnTotalAppmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTotalAppmentsActionPerformed
       
        RbtnPendingAppments.setSelected(false);
 
        // getDoctorAppointments(id, false) = todas
        Response response = controllers.getAppointmentQueryController()
                .getDoctorAppointments(String.valueOf(doctorId), false);
 
        DefaultTableModel model = (DefaultTableModel) AppmentVisual.getModel();
        model.setRowCount(0);
        fillAppointmentTable(model, response);
    }//GEN-LAST:event_rbtnTotalAppmentsActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
       
        // Nombre exacto del JFrame: cboxAppmentID
        String appointmentId = cboxAppmentID.getItemAt(cboxAppmentID.getSelectedIndex());
        if (appointmentId == null || appointmentId.equals("Select one")) {
            showMessage("Please select an appointment.", false);
            return;
        }
 
        Response response = controllers.getAppointmentManagementController()
                .acceptAppointment(appointmentId);
 
        if (response.getStatus() == Status.OK) {
            showMessage("Appointment accepted.", true);
            loadAppointmentComboBoxes();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
       String appointmentId = cboxAppmentComplete.getItemAt(cboxAppmentComplete.getSelectedIndex());
        String diagnosis     = AtxtDiagnosis.getText();
        String observations  = AtxtObservations.getText();
        String treatment     = atxtTreatmennt.getText();   // atxtTreatmennt (doble n)
        String followUp      = AtxtIndication.getText();
 
        Response response = controllers.getAppointmentManagementController()
                .completeAppointment(appointmentId, diagnosis, observations, treatment, followUp);
 
        if (response.getStatus() == Status.OK) {
            showMessage("Appointment completed.", true);
            clearCompleteFields();
            loadAppointmentComboBoxes();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void btnPrescribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrescribeActionPerformed
        DefaultTableModel model = (DefaultTableModel) prescribeMedicationsTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnPrescribeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String appointmentId = cbappmentIDmedications.getItemAt(cbappmentIDmedications.getSelectedIndex());
        String medName       = txtMedicationName.getText();   // txtMedicationName es JTextField
        String dose          = fieldDose.getText();
        String route         = fieldadminroute.getText();
        String duration      = fieldTreatmentDuration.getText();
        String instructions  = fieldAddInstructions.getText();
        String frequency     = fieldFrecuency.getText();
 
        Response response = controllers.getPrescriptionController()
                .addPrescription(appointmentId, medName, dose, route, duration, instructions, frequency);
 
        if (response.getStatus() == Status.OK || response.getStatus() == Status.CREATED) {
            DefaultTableModel model = (DefaultTableModel) prescribeMedicationsTable.getModel();
            model.addRow(new Object[]{
                appointmentId, medName, dose, route, duration, instructions, frequency
            });
            showMessage("Medication added.", true);
            clearPrescriptionFields();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAcceptRescheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptRescheduleActionPerformed
        String appointmentId = cboxAppment.getItemAt(cboxAppment.getSelectedIndex());
        String newTime       = fieldNewtimeappment.getText();
        String reason        = fieldReasonAppment.getText();
 
        Response response = controllers.getAppointmentManagementController()
                .rescheduleAppointment(appointmentId, newTime, reason);
 
        if (response.getStatus() == Status.OK) {
            showMessage("Appointment rescheduled.", true);
            fieldNewtimeappment.setText("");
            fieldReasonAppment.setText("");
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnAcceptRescheduleActionPerformed
 private void loadDoctorData() {
        Response response = controllers.getAuthController()
                .getUser(String.valueOf(doctorId));
 
        if (response.getStatus() == Status.OK && response.getData() != null) {
            java.util.HashMap<String, Object> data = response.getData();
            // Nombres exactos del JFrame
            fielFirstname.setText(safe(data.get("firstname")));
            fieldLastname.setText(safe(data.get("lastname")));
            fieldLicenseNumber.setText(safe(data.get("licenceNumber")));
            fieldAssignedOffice.setText(safe(data.get("assignedOffice")));
            fieldUser.setText(safe(data.get("username")));
 
            String specialty = safe(data.get("specialty"));
            for (int i = 0; i < cboxSpecialty.getItemCount(); i++) {
                String item = cboxSpecialty.getItemAt(i)
                        .replaceAll(" & ", "").replaceAll(" ", "_");
                if (item.equals(specialty)) {
                    cboxSpecialty.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
 private void loadPatientComboBoxes() {
        // Nombres exactos del JFrame: cboxPatient, cboxPatientID
        cboxPatient.removeAllItems();   cboxPatient.addItem("Select one");
        cboxPatientID.removeAllItems(); cboxPatientID.addItem("Select one");
 
        Response response = controllers.getPatientController().getAllPatients();
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("patients");
            if (list instanceof java.util.ArrayList) {
                for (Object obj : (java.util.ArrayList<?>) list) {
                    if (obj instanceof User) {
                        String pid = String.valueOf(((User) obj).getId());
                        cboxPatient.addItem(pid);
                        cboxPatientID.addItem(pid);
                    }
                }
            }
        }
    }
 
    private void loadAppointmentComboBoxes() {
        // Nombres exactos del JFrame: cboxAppmentID, cboxAppmentComplete,
        //                             cbappmentIDmedications, cboxAppment
        cboxAppmentID.removeAllItems();          cboxAppmentID.addItem("Select one");
        cboxAppmentComplete.removeAllItems();    cboxAppmentComplete.addItem("Select one");
        cbappmentIDmedications.removeAllItems(); cbappmentIDmedications.addItem("Select one");
        cboxAppment.removeAllItems();            cboxAppment.addItem("Select one");
 
        Response response = controllers.getDoctorController()
                .getDoctorAppointmentIds(String.valueOf(doctorId));
 
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("appointmentIds");
            if (list instanceof java.util.ArrayList) {
                for (Object id : (java.util.ArrayList<?>) list) {
                    String sid = String.valueOf(id);
                    cboxAppmentID.addItem(sid);
                    cboxAppmentComplete.addItem(sid);
                    cbappmentIDmedications.addItem(sid);
                    cboxAppment.addItem(sid);
                }
            }
        }
    }
 
    private void loadHospitalizationComboBox() {
        // Nombre exacto del JFrame: xboxRequest
        xboxRequest.removeAllItems();
        xboxRequest.addItem("Select one");
 
        Response response = controllers.getHospitalizationQueryController()
                .getDoctorHospitalizations(String.valueOf(doctorId));
 
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("hospitalizationIds");
            if (list instanceof java.util.ArrayList) {
                for (Object id : (java.util.ArrayList<?>) list) {
                    xboxRequest.addItem(String.valueOf(id));
                }
            }
        }
    }
 
    // ── HELPERS ───────────────────────────────────────────────────────
 
    private void fillAppointmentTable(DefaultTableModel model, Response response) {
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("appointments");
            if (list instanceof java.util.ArrayList) {
                for (Object row : (java.util.ArrayList<?>) list) {
                    if (row instanceof Object[]) {
                        model.addRow((Object[]) row);
                    }
                }
            }
        }
    }
 
    private void showMessage(String message, boolean success) {
        int type = success ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(this, message, success ? "Success" : "Error", type);
    }
 
    private String safe(Object obj) {
        return obj != null ? obj.toString() : "";
    }
 
    private void clearCompleteFields() {
        AtxtDiagnosis.setText("");
        AtxtObservations.setText("");
        atxtTreatmennt.setText("");
        AtxtIndication.setText("");
    }
 
    private void clearGenerateFields() {
        atxtReason.setText("");
        AtxtObservationsHospital.setText("");
        fieldEntry.setText("");
    }
 
    private void clearPrescriptionFields() {
        txtMedicationName.setText("");
        fieldDose.setText("");
        fieldadminroute.setText("");
        fieldTreatmentDuration.setText("");
        fieldAddInstructions.setText("");
        fieldFrecuency.setText("");
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AppmentHistory;
    private javax.swing.JTable AppmentVisual;
    private javax.swing.JTextArea AtxtDiagnosis;
    private javax.swing.JTextArea AtxtIndication;
    private javax.swing.JTextArea AtxtObservations;
    private javax.swing.JTextArea AtxtObservationsHospital;
    private javax.swing.JRadioButton RbtnPendingAppments;
    private javax.swing.JScrollPane ScrollAppmentVisual;
    private javax.swing.JScrollPane ScrollDiagnosis;
    private javax.swing.JScrollPane ScrollHistoryAppment;
    private javax.swing.JScrollPane ScrollIndication;
    private javax.swing.JScrollPane ScrollMedications;
    private javax.swing.JScrollPane ScrollObservations;
    private javax.swing.JScrollPane ScrollObservationsHospital;
    private javax.swing.JScrollPane ScrollReason;
    private javax.swing.JScrollPane ScrollTreatment;
    private javax.swing.JSeparator SeparatorCenter;
    private javax.swing.JSeparator SeparatorRight;
    private javax.swing.JSeparator Separatorleft;
    private javax.swing.JTabbedPane TpaneDoctorView;
    private javax.swing.JLabel appmentID;
    private javax.swing.JTextArea atxtReason;
    private javax.swing.JTextArea atxtTreatmennt;
    private javax.swing.JPanel background;
    private javax.swing.JPanel backgroundRquest;
    private javax.swing.JPanel bgAppment;
    private javax.swing.JPanel bgMedications;
    private javax.swing.JPanel bgModifyInfo;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAcceptReschedule;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrescribe;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbappmentIDmedications;
    private javax.swing.JComboBox<String> cboxAppment;
    private javax.swing.JComboBox<String> cboxAppmentComplete;
    private javax.swing.JComboBox<String> cboxAppmentID;
    private javax.swing.JComboBox<String> cboxPatient;
    private javax.swing.JComboBox<String> cboxPatientID;
    private javax.swing.JComboBox<String> cboxSpecialty;
    private javax.swing.JTextField fielFirstname;
    private javax.swing.JTextField fieldAddInstructions;
    private javax.swing.JTextField fieldAssignedOffice;
    private javax.swing.JTextField fieldDose;
    private javax.swing.JTextField fieldDuration;
    private javax.swing.JTextField fieldEntry;
    private javax.swing.JTextField fieldFrecuency;
    private javax.swing.JTextField fieldLastname;
    private javax.swing.JTextField fieldLicenseNumber;
    private javax.swing.JTextField fieldNewtimeappment;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldPasswordConfirm;
    private javax.swing.JTextField fieldReasonAppment;
    private javax.swing.JTextField fieldTreatmentDuration;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JTextField fieldadminroute;
    private packagee.core.models.PanelRound historyAppmentPanel;
    private packagee.core.models.PanelRound panelUp;
    private javax.swing.JTable prescribeMedicationsTable;
    private javax.swing.JRadioButton rbtnPatientID;
    private javax.swing.JRadioButton rbtnRequest;
    private javax.swing.JRadioButton rbtnTotalAppments;
    private javax.swing.JLabel txtAddInstructions;
    private javax.swing.JLabel txtApmment;
    private javax.swing.JLabel txtAppmentComplete;
    private javax.swing.JLabel txtAppmentID;
    private javax.swing.JLabel txtAssignedOffice;
    private javax.swing.JLabel txtCompleteMedicalAppment;
    private javax.swing.JLabel txtDiagnosis;
    private javax.swing.JLabel txtDoctorView;
    private javax.swing.JLabel txtDose;
    private javax.swing.JLabel txtDuration;
    private javax.swing.JLabel txtEntry;
    private javax.swing.JLabel txtFirstname;
    private javax.swing.JLabel txtFrecuency;
    private javax.swing.JLabel txtHospitalReason;
    private javax.swing.JLabel txtHospitalization;
    private javax.swing.JLabel txtIndication;
    private javax.swing.JLabel txtLastname;
    private javax.swing.JLabel txtLicenseNumber;
    private javax.swing.JTextField txtMedicationName;
    private javax.swing.JLabel txtNewtimeAppment;
    private javax.swing.JLabel txtObservations;
    private javax.swing.JLabel txtObservationsHospital;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtPasswordConfirm;
    private javax.swing.JLabel txtPatient;
    private javax.swing.JLabel txtRcommendedtreatment;
    private javax.swing.JLabel txtReasonAppment;
    private javax.swing.JLabel txtReschedule;
    private javax.swing.JLabel txtSpecialty;
    private javax.swing.JLabel txtTrmentDuration;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel txtadminroute;
    private javax.swing.JLabel txtmedicalAppment;
    private javax.swing.JLabel txtmedicationName;
    private javax.swing.JComboBox<String> xboxRequest;
    // End of variables declaration//GEN-END:variables
}
