/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee.core.views;

import java.awt.Color;
import javax.swing.JOptionPane;
import packagee.core.controllers.utils.ControllerContainer;
import packagee.core.controllers.utils.Response;
import packagee.core.controllers.utils.Status;

public class LoginView extends javax.swing.JFrame {

    // ── CAMPOS PRIVADOS ───────────────────────────────────────────────
    private int x, y;
    private final ControllerContainer controllers;

    // ── CONSTRUCTOR ───────────────────────────────────────────────────
    public LoginView(ControllerContainer controllers) {
        initComponents();
        this.controllers = controllers;
        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rightScroll = new packagee.core.models.PanelRound();
        upScroll = new packagee.core.models.PanelRound();
        btnClose = new javax.swing.JButton();
        tbbLogin = new javax.swing.JTabbedPane();
        banckgroundlogin = new packagee.core.models.PanelRound();
        txtLogin = new javax.swing.JLabel();
        FieldUsername = new javax.swing.JTextField();
        txtUsername = new javax.swing.JLabel();
        FieldPassword = new javax.swing.JTextField();
        txtPassword = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        backgorund = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JLabel();
        fieldFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JLabel();
        fieldLastname = new javax.swing.JTextField();
        txtID = new javax.swing.JLabel();
        fieldID = new javax.swing.JTextField();
        txtGender = new javax.swing.JLabel();
        txtPhone = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        txtUser = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        fieldPacientPassword = new javax.swing.JTextField();
        txtPacientPassword = new javax.swing.JLabel();
        txtPswordConfirm = new javax.swing.JLabel();
        fieldPswordConfirm = new javax.swing.JTextField();
        CboxGender = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        txtAdrdress = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        txtBirthdate = new javax.swing.JLabel();
        fieldBirthdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rightScroll.setRadius(50);

        upScroll.setRadius(50);
        upScroll.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                upScrollMouseDragged(evt);
            }
        });
        upScroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                upScrollMousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upScrollLayout = new javax.swing.GroupLayout(upScroll);
        upScroll.setLayout(upScrollLayout);
        upScrollLayout.setHorizontalGroup(
            upScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upScrollLayout.createSequentialGroup()
                .addContainerGap(997, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        upScrollLayout.setVerticalGroup(
            upScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtLogin.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        txtLogin.setText("LOGIN");

        FieldUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FieldUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtUsername.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUsername.setText("USERNAME");

        FieldPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        FieldPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPassword.setText("PASSWORD");

        btnEnter.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout banckgroundloginLayout = new javax.swing.GroupLayout(banckgroundlogin);
        banckgroundlogin.setLayout(banckgroundloginLayout);
        banckgroundloginLayout.setHorizontalGroup(
            banckgroundloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, banckgroundloginLayout.createSequentialGroup()
                .addContainerGap(475, Short.MAX_VALUE)
                .addComponent(txtLogin)
                .addGap(481, 481, 481))
            .addGroup(banckgroundloginLayout.createSequentialGroup()
                .addGroup(banckgroundloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(banckgroundloginLayout.createSequentialGroup()
                        .addGap(431, 431, 431)
                        .addGroup(banckgroundloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, banckgroundloginLayout.createSequentialGroup()
                                .addGroup(banckgroundloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, banckgroundloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(banckgroundloginLayout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(btnEnter)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        banckgroundloginLayout.setVerticalGroup(
            banckgroundloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(banckgroundloginLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(txtLogin)
                .addGap(74, 74, 74)
                .addComponent(txtUsername)
                .addGap(18, 18, 18)
                .addComponent(FieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword)
                .addGap(18, 18, 18)
                .addComponent(FieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnEnter)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        tbbLogin.addTab("Login", banckgroundlogin);

        txtFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtFirstname.setText("Firstname");

        fieldFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLastname.setText("Lastname");

        fieldLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtID.setText("ID");

        fieldID.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtGender.setText("Gender");

        txtPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPhone.setText("Phone");

        fieldPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtEmail.setText("Email");

        fieldEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUser.setText("User");

        fieldUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        fieldPacientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPacientPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPacientPassword.setText("Password");

        txtPswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPswordConfirm.setText("Password confirmation");

        fieldPswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        fieldPswordConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPswordConfirmActionPerformed(evt);
            }
        });

        CboxGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        btnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtAdrdress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAdrdress.setText("Address");

        fieldAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtBirthdate.setText("Birthdate");

        fieldBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout backgorundLayout = new javax.swing.GroupLayout(backgorund);
        backgorund.setLayout(backgorundLayout);
        backgorundLayout.setHorizontalGroup(
            backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgorundLayout.createSequentialGroup()
                .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgorundLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(txtPacientPassword))
                    .addGroup(backgorundLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldPacientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgorundLayout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(txtUser))
                    .addGroup(backgorundLayout.createSequentialGroup()
                        .addGap(432, 432, 432)
                        .addComponent(fieldPswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgorundLayout.createSequentialGroup()
                        .addGap(456, 456, 456)
                        .addComponent(btnSave))
                    .addGroup(backgorundLayout.createSequentialGroup()
                        .addGap(396, 396, 396)
                        .addComponent(txtPswordConfirm))
                    .addGroup(backgorundLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(backgorundLayout.createSequentialGroup()
                                .addComponent(txtBirthdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgorundLayout.createSequentialGroup()
                                .addComponent(txtFirstname)
                                .addGap(34, 34, 34)
                                .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastname)
                            .addComponent(txtAdrdress))
                        .addGap(18, 18, 18)
                        .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(backgorundLayout.createSequentialGroup()
                                .addComponent(fieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtID)
                                .addGap(30, 30, 30)
                                .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGender)
                                .addGap(26, 26, 26)
                                .addComponent(CboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(backgorundLayout.createSequentialGroup()
                                .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhone)
                                .addGap(18, 18, 18)
                                .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmail)
                                .addGap(18, 18, 18)
                                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        backgorundLayout.setVerticalGroup(
            backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgorundLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname)
                    .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastname)
                    .addComponent(fieldLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID)
                    .addComponent(fieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGender)
                    .addComponent(CboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBirthdate)
                        .addComponent(fieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAdrdress)
                        .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPhone)
                        .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgorundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmail)
                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(txtUser)
                .addGap(18, 18, 18)
                .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPacientPassword)
                .addGap(18, 18, 18)
                .addComponent(fieldPacientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPswordConfirm)
                .addGap(18, 18, 18)
                .addComponent(fieldPswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnSave)
                .addGap(42, 42, 42))
        );

        tbbLogin.addTab("Patient register", backgorund);

        javax.swing.GroupLayout rightScrollLayout = new javax.swing.GroupLayout(rightScroll);
        rightScroll.setLayout(rightScrollLayout);
        rightScrollLayout.setHorizontalGroup(
            rightScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(rightScrollLayout.createSequentialGroup()
                .addComponent(tbbLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        rightScrollLayout.setVerticalGroup(
            rightScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightScrollLayout.createSequentialGroup()
                .addComponent(upScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbbLogin)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upScrollMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upScrollMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_upScrollMousePressed

    private void upScrollMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upScrollMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_upScrollMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        String username = FieldUsername.getText();
        String password = FieldPassword.getText();

        Response response = controllers.getAuthController().login(username, password);

        if (response.getStatus() != Status.OK) {
            showMessage(response.getMessage(), false);
            return;
        }

        String role = (String) response.getData().get("role");
        long userId = ((Number) response.getData().get("id")).longValue();

        this.setVisible(false);

        switch (role) {
            case "ADMIN":
                new AdminView(controllers).setVisible(true);
                break;
            case "DOCTOR":
                new DoctorView(controllers, userId).setVisible(true);
                break;
            default: // PATIENT
                new PatientView(controllers, userId).setVisible(true);
                break;
        }

    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        // Nombres exactos del JFrame
        String id = fieldID.getText();
        String username = fieldUser.getText();
        String first = fieldFirstname.getText();
        String last = fieldLastname.getText();
        String password = fieldPacientPassword.getText();
        String confirm = fieldPswordConfirm.getText();
        String email = fieldEmail.getText();
        String birth = fieldBirthdate.getText();
        String gender = CboxGender.getSelectedIndex() == 1 ? "true" : "false";
        String phone = fieldPhone.getText();
        String address = fieldAddress.getText();

        Response response = controllers.getPatientController().registerPatient(
                id, username, first, last,
                password, confirm,
                email, birth, gender, phone, address
        );

        if (response.getStatus() == Status.CREATED || response.getStatus() == Status.OK) {
            showMessage("Patient registered successfully!", true);
            clearRegisterFields();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void fieldPswordConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPswordConfirmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPswordConfirmActionPerformed
    private void showMessage(String message, boolean success) {
        int type = success ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(this, message, success ? "Success" : "Error", type);
    }

    private void clearRegisterFields() {
        fieldFirstname.setText("");
        fieldLastname.setText("");
        fieldID.setText("");
        fieldBirthdate.setText("");
        fieldAddress.setText("");
        fieldPhone.setText("");
        fieldEmail.setText("");
        fieldUser.setText("");
        fieldPacientPassword.setText("");
        fieldPswordConfirm.setText("");
        CboxGender.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboxGender;
    private javax.swing.JTextField FieldPassword;
    private javax.swing.JTextField FieldUsername;
    private javax.swing.JPanel backgorund;
    private packagee.core.models.PanelRound banckgroundlogin;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldBirthdate;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFirstname;
    private javax.swing.JTextField fieldID;
    private javax.swing.JTextField fieldLastname;
    private javax.swing.JTextField fieldPacientPassword;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPswordConfirm;
    private javax.swing.JTextField fieldUser;
    private packagee.core.models.PanelRound rightScroll;
    private javax.swing.JTabbedPane tbbLogin;
    private javax.swing.JLabel txtAdrdress;
    private javax.swing.JLabel txtBirthdate;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFirstname;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtLastname;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtPacientPassword;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtPswordConfirm;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel txtUsername;
    private packagee.core.models.PanelRound upScroll;
    // End of variables declaration//GEN-END:variables
}
