/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagee.core.views;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import packagee.core.controllers.utils.ControllerContainer;
import packagee.core.controllers.utils.Response;
import packagee.core.controllers.utils.Status;
import packagee.core.models.enums.RoomType;

public class PatientView extends javax.swing.JFrame implements packagee.core.models.storage.IStorageObserver {

    // ── CAMPOS PRIVADOS ───────────────────────────────────────────────
    private int x, y;
    private final ControllerContainer controllers;
    private final long patientId;
    private final boolean isFromAdmin;

    // ── CONSTRUCTOR DESDE LOGIN DIRECTO ───────────────────────────────
    public PatientView(ControllerContainer controllers, long patientId) {
        this(controllers, patientId, false);
    }

    // ── CONSTRUCTOR DESDE ADMINVIEW (Back habilitado) ─────────────────
    public PatientView(ControllerContainer controllers, long patientId, boolean isFromAdmin) {
        initComponents();
        this.controllers = controllers;
        this.patientId = patientId;
        this.isFromAdmin = isFromAdmin;

        this.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);

        
        btnBack.setVisible(isFromAdmin);

        
        loadPatientData();

        
        loadAttendingDoctorComboBox();
        loadRoomTypeComboBox();
        loadAppointmentIdComboBox();
        btnRefreshActionPerformed(null);
        controllers.getStorage().addObserver(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    public void onStorageChanged(String eventType) {
        if (eventType.equals("APPOINTMENT_CHANGED")) {
            btnRefreshActionPerformed(null);
            loadAppointmentIdComboBox();
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPatienview = new packagee.core.models.PanelRound();
        panelUp = new packagee.core.models.PanelRound();
        btnClose = new javax.swing.JButton();
        txtPatientview = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        tbbdPatientInfo = new javax.swing.JTabbedPane();
        bgpanel = new javax.swing.JPanel();
        ScrollAppmentHistory = new javax.swing.JScrollPane();
        TableAppointmentHistory = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        txtFirstname = new javax.swing.JLabel();
        fieldFirstname = new javax.swing.JTextField();
        txtLastname = new javax.swing.JLabel();
        labelLastname = new javax.swing.JTextField();
        txtBirthdate = new javax.swing.JLabel();
        fieldBirthdate = new javax.swing.JTextField();
        txtGender = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JTextField();
        txtPassword = new javax.swing.JLabel();
        txtPasswordConfirm = new javax.swing.JLabel();
        fieldPasswordConfirm = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        fieldUser = new javax.swing.JTextField();
        CboxGender = new javax.swing.JComboBox<>();
        bgroundRquest = new javax.swing.JPanel();
        txtRequestMedical = new javax.swing.JLabel();
        rbtnSpecialty = new javax.swing.JRadioButton();
        rbtnDoctor = new javax.swing.JRadioButton();
        SeparatorLeft = new javax.swing.JSeparator();
        txtappmentDate = new javax.swing.JLabel();
        fieldAppmentDate = new javax.swing.JTextField();
        fieldAppmentReason = new javax.swing.JTextField();
        txtAppmentTime = new javax.swing.JLabel();
        txtAppmentType = new javax.swing.JLabel();
        txtAppmentReason = new javax.swing.JLabel();
        cboxAppmentType = new javax.swing.JComboBox<>();
        btnCreateAppoiment = new javax.swing.JButton();
        SeparatorRight = new javax.swing.JSeparator();
        txtRquestHospital = new javax.swing.JLabel();
        txtHospitalReason = new javax.swing.JLabel();
        txtattdingDoctor = new javax.swing.JLabel();
        cboxAttndingDoctor = new javax.swing.JComboBox<>();
        fielDateEstimated = new javax.swing.JTextField();
        txtDateEstimated = new javax.swing.JLabel();
        txtDesiredRoom = new javax.swing.JLabel();
        cboxDesiredRoom = new javax.swing.JComboBox<>();
        txtObservations = new javax.swing.JLabel();
        ScrollObservations = new javax.swing.JScrollPane();
        AtxtObservations = new javax.swing.JTextArea();
        btnCreateHospitalization = new javax.swing.JButton();
        txtCancelAppment = new javax.swing.JLabel();
        txtIDAppment = new javax.swing.JLabel();
        txtCancelObservations = new javax.swing.JLabel();
        ScrollCancelObservations = new javax.swing.JScrollPane();
        AtxtCancelObservations = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        ScrollHospitalizationReason = new javax.swing.JScrollPane();
        AtxtHospitalreason = new javax.swing.JTextArea();
        ScrollAppmentReason = new javax.swing.JScrollPane();
        AtxtAppmentReason = new javax.swing.JTextArea();
        cboxIDAppment = new javax.swing.JComboBox<>();
        CboxSpecialty = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        BackgroundPatienview.setRadius(50);

        panelUp.setRadius(50);
        panelUp.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelUpMouseDragged(evt);
            }
        });
        panelUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelUpMousePressed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnClose.setText("X");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClose.setFocusable(false);
        btnClose.setRequestFocusEnabled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtPatientview.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPatientview.setText("PATIENT VIEW");

        btnBack.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUpLayout = new javax.swing.GroupLayout(panelUp);
        panelUp.setLayout(panelUpLayout);
        panelUpLayout.setHorizontalGroup(
            panelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtPatientview)
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(19, 19, 19))
        );
        panelUpLayout.setVerticalGroup(
            panelUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose))
            .addGroup(panelUpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(txtPatientview, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TableAppointmentHistory.setAutoCreateRowSorter(true);
        TableAppointmentHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Doctor", "Specialty", "Type", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollAppmentHistory.setViewportView(TableAppointmentHistory);

        btnRefresh.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgpanelLayout = new javax.swing.GroupLayout(bgpanel);
        bgpanel.setLayout(bgpanelLayout);
        bgpanelLayout.setHorizontalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(ScrollAppmentHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGap(602, 602, 602)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(78, 78, 78))
        );
        bgpanelLayout.setVerticalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(ScrollAppmentHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbbdPatientInfo.addTab("Appointment history", bgpanel);

        txtFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtFirstname.setText("Firstname");

        fieldFirstname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtLastname.setText("Lastname");

        labelLastname.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtBirthdate.setText("Birthdate");

        fieldBirthdate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtGender.setText("Gender");

        txtEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtEmail.setText("Email");

        fieldEmail.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPhone.setText("Phone");

        fieldPhone.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAddress.setText("Address");

        fieldAddress.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        fieldPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPassword.setText("Password");

        txtPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtPasswordConfirm.setText("Password confirmation");

        fieldPasswordConfirm.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        btnSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtUser.setText("User");

        fieldUser.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        CboxGender.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CboxGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Female", "Male" }));

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(txtFirstname)
                .addGap(18, 18, 18)
                .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtLastname)
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(txtPhone)
                        .addGap(18, 18, 18)
                        .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAddress)
                        .addGap(18, 18, 18)
                        .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(labelLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBirthdate)
                        .addGap(18, 18, 18)
                        .addComponent(fieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(141, 141, 141))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(516, 516, 516)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnSave))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(fieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPasswordConfirm)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(txtPassword))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(backgroundLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(txtUser)))
                            .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname)
                    .addComponent(fieldFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastname)
                    .addComponent(labelLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirthdate)
                    .addComponent(fieldBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGender)
                    .addComponent(txtEmail)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CboxGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress)
                    .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addComponent(txtUser)
                .addGap(18, 18, 18)
                .addComponent(fieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPassword)
                .addGap(18, 18, 18)
                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordConfirm)
                .addGap(18, 18, 18)
                .addComponent(fieldPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnSave)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        tbbdPatientInfo.addTab("Modify info", background);

        txtRequestMedical.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRequestMedical.setText("Request medical appointment");

        rbtnSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbtnSpecialty.setText("Specialty");
        rbtnSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSpecialtyActionPerformed(evt);
            }
        });

        rbtnDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        rbtnDoctor.setText("Doctor");
        rbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnDoctorActionPerformed(evt);
            }
        });

        SeparatorLeft.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtappmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtappmentDate.setText("Appointment date");

        fieldAppmentDate.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        fieldAppmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtAppmentTime.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAppmentTime.setText("Appointment time");

        txtAppmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAppmentType.setText("Appointment type");

        txtAppmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtAppmentReason.setText("Appointment reason");

        cboxAppmentType.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxAppmentType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Remote", "In-person" }));

        btnCreateAppoiment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCreateAppoiment.setText("Create");
        btnCreateAppoiment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAppoimentActionPerformed(evt);
            }
        });

        SeparatorRight.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtRquestHospital.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtRquestHospital.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRquestHospital.setText("Request hospitalization");

        txtHospitalReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtHospitalReason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHospitalReason.setText("Hospitalization reason");

        txtattdingDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtattdingDoctor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtattdingDoctor.setText("Attending doctor");

        cboxAttndingDoctor.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxAttndingDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        fielDateEstimated.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtDateEstimated.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDateEstimated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDateEstimated.setText("Estimated date of admission");
        txtDateEstimated.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtDesiredRoom.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtDesiredRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDesiredRoom.setText("Desired room type");

        cboxDesiredRoom.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxDesiredRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        txtObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtObservations.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtObservations.setText("Observations");

        AtxtObservations.setColumns(20);
        AtxtObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtObservations.setRows(5);
        ScrollObservations.setViewportView(AtxtObservations);

        btnCreateHospitalization.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCreateHospitalization.setText("Create");
        btnCreateHospitalization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHospitalizationActionPerformed(evt);
            }
        });

        txtCancelAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCancelAppment.setText("Cancel appointment");

        txtIDAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtIDAppment.setText("ID appointment");

        txtCancelObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        txtCancelObservations.setText("Observations");

        AtxtCancelObservations.setColumns(20);
        AtxtCancelObservations.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtCancelObservations.setRows(5);
        ScrollCancelObservations.setViewportView(AtxtCancelObservations);

        btnCancel.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        AtxtHospitalreason.setColumns(20);
        AtxtHospitalreason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtHospitalreason.setRows(5);
        ScrollHospitalizationReason.setViewportView(AtxtHospitalreason);

        AtxtAppmentReason.setColumns(20);
        AtxtAppmentReason.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        AtxtAppmentReason.setRows(5);
        ScrollAppmentReason.setViewportView(AtxtAppmentReason);

        cboxIDAppment.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        cboxIDAppment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));

        CboxSpecialty.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        CboxSpecialty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one" }));
        CboxSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboxSpecialtyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgroundRquestLayout = new javax.swing.GroupLayout(bgroundRquest);
        bgroundRquest.setLayout(bgroundRquestLayout);
        bgroundRquestLayout.setHorizontalGroup(
            bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgroundRquestLayout.createSequentialGroup()
                .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(bgroundRquestLayout.createSequentialGroup()
                            .addGap(44, 44, 44)
                            .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(bgroundRquestLayout.createSequentialGroup()
                                    .addComponent(rbtnSpecialty)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbtnDoctor))
                                .addGroup(bgroundRquestLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(fieldAppmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgroundRquestLayout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtAppmentTime)
                                        .addComponent(txtappmentDate)
                                        .addComponent(CboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(bgroundRquestLayout.createSequentialGroup()
                                    .addGap(63, 63, 63)
                                    .addComponent(fieldAppmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(bgroundRquestLayout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(txtAppmentReason))
                                .addGroup(bgroundRquestLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(txtAppmentType))
                                .addGroup(bgroundRquestLayout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(cboxAppmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(bgroundRquestLayout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(txtRequestMedical)))
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(ScrollAppmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnCreateAppoiment)))
                .addGap(66, 66, 66)
                .addComponent(SeparatorLeft, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgroundRquestLayout.createSequentialGroup()
                            .addGap(211, 211, 211)
                            .addComponent(btnCreateHospitalization))
                        .addGroup(bgroundRquestLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHospitalReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ScrollHospitalizationReason, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(txtRquestHospital, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                .addComponent(txtattdingDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgroundRquestLayout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDateEstimated, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ScrollObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDesiredRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(cboxAttndingDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(fielDateEstimated, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(cboxDesiredRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(SeparatorRight, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollCancelObservations, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgroundRquestLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtCancelAppment))
                            .addGroup(bgroundRquestLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(btnCancel))
                            .addGroup(bgroundRquestLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboxIDAppment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDAppment)))
                            .addGroup(bgroundRquestLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(txtCancelObservations)))
                        .addGap(49, 49, 49)))
                .addGap(81, 81, 81))
        );
        bgroundRquestLayout.setVerticalGroup(
            bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SeparatorLeft)
            .addComponent(SeparatorRight)
            .addGroup(bgroundRquestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addComponent(txtRquestHospital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(txtHospitalReason)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollHospitalizationReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtattdingDoctor)
                        .addGap(18, 18, 18)
                        .addComponent(cboxAttndingDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDateEstimated)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fielDateEstimated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtDesiredRoom)
                        .addGap(18, 18, 18)
                        .addComponent(cboxDesiredRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtObservations)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ScrollObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCreateHospitalization)
                        .addGap(15, 15, 15))
                    .addGroup(bgroundRquestLayout.createSequentialGroup()
                        .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgroundRquestLayout.createSequentialGroup()
                                .addComponent(txtRequestMedical)
                                .addGap(18, 18, 18)
                                .addGroup(bgroundRquestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rbtnSpecialty)
                                    .addComponent(rbtnDoctor))
                                .addGap(18, 18, 18)
                                .addComponent(CboxSpecialty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtappmentDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldAppmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(txtAppmentTime)
                                .addGap(18, 18, 18)
                                .addComponent(fieldAppmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAppmentReason)
                                .addGap(24, 24, 24)
                                .addComponent(ScrollAppmentReason, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgroundRquestLayout.createSequentialGroup()
                                .addComponent(txtCancelAppment)
                                .addGap(39, 39, 39)
                                .addComponent(txtIDAppment)
                                .addGap(18, 18, 18)
                                .addComponent(cboxIDAppment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCancelObservations)
                                .addGap(18, 18, 18)
                                .addComponent(ScrollCancelObservations, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnCancel)))
                        .addGap(18, 18, 18)
                        .addComponent(txtAppmentType)
                        .addGap(18, 18, 18)
                        .addComponent(cboxAppmentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCreateAppoiment)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tbbdPatientInfo.addTab("Request/Cancel", bgroundRquest);

        javax.swing.GroupLayout BackgroundPatienviewLayout = new javax.swing.GroupLayout(BackgroundPatienview);
        BackgroundPatienview.setLayout(BackgroundPatienviewLayout);
        BackgroundPatienviewLayout.setHorizontalGroup(
            BackgroundPatienviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tbbdPatientInfo)
        );
        BackgroundPatienviewLayout.setVerticalGroup(
            BackgroundPatienviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundPatienviewLayout.createSequentialGroup()
                .addComponent(panelUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbbdPatientInfo))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPatienview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPatienview, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUpMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_panelUpMousePressed

    private void panelUpMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUpMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panelUpMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        String appointmentId = cboxIDAppment.getItemAt(cboxIDAppment.getSelectedIndex());
        if (appointmentId == null || appointmentId.equals("Select one")) {
            showMessage("Please select an appointment.", false);
            return;
        }

        Response response = controllers.getAppointmentManagementController()
                .cancelAppointment(appointmentId);

        if (response.getStatus() == Status.OK) {
            showMessage("Appointment cancelled.", true);
            loadAppointmentIdComboBox();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String first = fieldFirstname.getText();
        String last = labelLastname.getText();   // labelLastname es un JTextField
        String gender = CboxGender.getSelectedIndex() == 1 ? "Female" : "Male";
        String birth = fieldBirthdate.getText();
        String address = fieldAddress.getText();
        String phone = fieldPhone.getText();
        String email = fieldEmail.getText();
        String username = fieldUser.getText();
        String password = fieldPassword.getText();
        String confirm = fieldPasswordConfirm.getText();

        Response response = controllers.getPatientController().updatePatient(
                String.valueOf(patientId),
                username, first, last,
                password, confirm,
                email, birth, gender, phone, address
        );

        if (response.getStatus() == Status.OK) {
            showMessage("Profile updated successfully!", true);
        } else {
            showMessage(response.getMessage(), false);
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        controllers.getStorage().removeObserver(this);
        this.setVisible(false);
        new LoginView(controllers).setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        controllers.getStorage().removeObserver(this);
        this.setVisible(false);
        new AdminView(controllers).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void rbtnSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSpecialtyActionPerformed
        rbtnDoctor.setSelected(false);
        CboxSpecialty.removeAllItems();
        CboxSpecialty.addItem("Select one");
        for (packagee.core.models.enums.Specialty spec : packagee.core.models.enums.Specialty.values()) {
            CboxSpecialty.addItem(spec.toString().replaceAll("_", " & "));
        }
    }//GEN-LAST:event_rbtnSpecialtyActionPerformed

    private void rbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnDoctorActionPerformed
        rbtnSpecialty.setSelected(false);
        CboxSpecialty.removeAllItems();
        CboxSpecialty.addItem("Select one");
        Response response = controllers.getDoctorController().getAllDoctors();
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("doctors");
            if (list instanceof java.util.ArrayList) {
                for (Object obj : (java.util.ArrayList<?>) list) {
                    if (obj instanceof java.util.HashMap) {
                        java.util.HashMap<?, ?> d = (java.util.HashMap<?, ?>) obj;
                        CboxSpecialty.addItem(d.get("id") + " - " + d.get("firstname") + " " + d.get("lastname"));
                    }
                }
            }
        }
    }//GEN-LAST:event_rbtnDoctorActionPerformed

    private void btnCreateAppoimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAppoimentActionPerformed
        String selected = CboxSpecialty.getItemAt(CboxSpecialty.getSelectedIndex());
        String date = fieldAppmentDate.getText();
        String hour = fieldAppmentReason.getText();
        String reason = AtxtAppmentReason.getText();
        String type = cboxAppmentType.getItemAt(cboxAppmentType.getSelectedIndex());

        Response response;
        if (rbtnDoctor.isSelected()) {
            String doctorId = selected == null ? "" : selected.split(" - ")[0].trim();
            response = controllers.getAppointmentRequestController()
                    .requestAppointmentByDoctor(String.valueOf(patientId), doctorId, date, hour, type, reason);
        } else {
            String specialtyEnum = selected == null ? "" : selected.replaceAll(" & ", "_").replaceAll(" ", "_");
            response = controllers.getAppointmentRequestController()
                    .requestAppointmentBySpecialty(String.valueOf(patientId), specialtyEnum, date, hour, type, reason);
        }

        if (response.getStatus() == Status.CREATED || response.getStatus() == Status.OK) {
            showMessage("Appointment created successfully!", true);
            clearAppointmentFields();
            loadAppointmentIdComboBox();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnCreateAppoimentActionPerformed


    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        Response response = controllers.getAppointmentQueryController()
                .getPatientAppointments(String.valueOf(patientId));

        DefaultTableModel model = (DefaultTableModel) TableAppointmentHistory.getModel();
        model.setRowCount(0);

        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("appointments");
            if (list instanceof java.util.ArrayList) {
                for (Object obj : (java.util.ArrayList<?>) list) {
                    if (obj instanceof java.util.HashMap) {
                        java.util.HashMap<?, ?> a = (java.util.HashMap<?, ?>) obj;
                        model.addRow(new Object[]{
                            a.get("id"), a.get("datetime"), a.get("doctor"),
                            a.get("specialty"), a.get("type"), a.get("status")
                        });
                    }
                }
            }
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnCreateHospitalizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHospitalizationActionPerformed
        String reason = AtxtHospitalreason.getText();
        String doctorId = cboxAttndingDoctor.getItemAt(cboxAttndingDoctor.getSelectedIndex());
        String estimatedDate = fielDateEstimated.getText();
        String roomType = cboxDesiredRoom.getItemAt(cboxDesiredRoom.getSelectedIndex());
        String observations = AtxtObservations.getText();

        if (doctorId != null && doctorId.contains(" - ")) {
            doctorId = doctorId.split(" - ")[0].trim();
        }

        Response response = controllers.getHospitalizationRequestController()
                .requestHospitalization(String.valueOf(patientId), doctorId, estimatedDate, reason, roomType, observations);

        if (response.getStatus() == Status.CREATED || response.getStatus() == Status.OK) {
            showMessage("Hospitalization request created!", true);
            clearHospitalizationFields();
        } else {
            showMessage(response.getMessage(), false);
        }
    }//GEN-LAST:event_btnCreateHospitalizationActionPerformed

    private void CboxSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboxSpecialtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboxSpecialtyActionPerformed

    private void loadPatientData() {
        Response response = controllers.getAuthController()
                .getUser(String.valueOf(patientId));

        if (response.getStatus() == Status.OK && response.getData() != null) {
            java.util.HashMap<String, Object> data = response.getData();
            // Nombres exactos del JFrame
            fieldFirstname.setText(safe(data.get("firstname")));
            labelLastname.setText(safe(data.get("lastname")));
            fieldBirthdate.setText(safe(data.get("birthdate")));
            fieldAddress.setText(safe(data.get("address")));
            fieldPhone.setText(safe(data.get("phone")));
            fieldEmail.setText(safe(data.get("email")));
            fieldUser.setText(safe(data.get("username")));
        }
    }

    private void loadAttendingDoctorComboBox() {
        cboxAttndingDoctor.removeAllItems();
        cboxAttndingDoctor.addItem("Select one");

        Response response = controllers.getDoctorController().getAllDoctors();
        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("doctors");
            if (list instanceof java.util.ArrayList) {
                for (Object obj : (java.util.ArrayList<?>) list) {
                    if (obj instanceof java.util.HashMap) {
                        java.util.HashMap<?, ?> d = (java.util.HashMap<?, ?>) obj;
                        String entry = d.get("id") + " - " + d.get("firstname") + " " + d.get("lastname");
                        cboxAttndingDoctor.addItem(entry);
                    }
                }
            }
        }
    }

    private void loadRoomTypeComboBox() {
        // Nombre exacto del JFrame: cboxDesiredRoom
        cboxDesiredRoom.removeAllItems();
        for (RoomType rt : RoomType.values()) {
            cboxDesiredRoom.addItem(rt.name());
        }
    }

    private void loadAppointmentIdComboBox() {
        // Nombre exacto del JFrame: cboxIDAppment
        cboxIDAppment.removeAllItems();
        cboxIDAppment.addItem("Select one");

        Response response = controllers.getPatientController()
                .getPatientAppointmentIds(String.valueOf(patientId));

        if (response.getStatus() == Status.OK && response.getData() != null) {
            Object list = response.getData().get("appointmentIds");
            if (list instanceof java.util.ArrayList) {
                for (Object id : (java.util.ArrayList<?>) list) {
                    cboxIDAppment.addItem(String.valueOf(id));
                }
            }
        }
    }

    // ── HELPERS ───────────────────────────────────────────────────────
    private void showMessage(String message, boolean success) {
        int type = success ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.ERROR_MESSAGE;
        JOptionPane.showMessageDialog(this, message, success ? "Success" : "Error", type);
    }

    private String safe(Object obj) {
        return obj != null ? obj.toString() : "";
    }

    private void clearAppointmentFields() {
        fieldAppmentDate.setText("");
        fieldAppmentReason.setText("");
        AtxtAppmentReason.setText("");
        CboxSpecialty.setSelectedIndex(0);
        cboxAppmentType.setSelectedIndex(0);
    }

    private void clearHospitalizationFields() {
        AtxtHospitalreason.setText("");
        fielDateEstimated.setText("");
        AtxtObservations.setText("");
        cboxAttndingDoctor.setSelectedIndex(0);
        cboxDesiredRoom.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AtxtAppmentReason;
    private javax.swing.JTextArea AtxtCancelObservations;
    private javax.swing.JTextArea AtxtHospitalreason;
    private javax.swing.JTextArea AtxtObservations;
    private packagee.core.models.PanelRound BackgroundPatienview;
    private javax.swing.JComboBox<String> CboxGender;
    private javax.swing.JComboBox<String> CboxSpecialty;
    private javax.swing.JScrollPane ScrollAppmentHistory;
    private javax.swing.JScrollPane ScrollAppmentReason;
    private javax.swing.JScrollPane ScrollCancelObservations;
    private javax.swing.JScrollPane ScrollHospitalizationReason;
    private javax.swing.JScrollPane ScrollObservations;
    private javax.swing.JSeparator SeparatorLeft;
    private javax.swing.JSeparator SeparatorRight;
    private javax.swing.JTable TableAppointmentHistory;
    private javax.swing.JPanel background;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JPanel bgroundRquest;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnCreateAppoiment;
    private javax.swing.JButton btnCreateHospitalization;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboxAppmentType;
    private javax.swing.JComboBox<String> cboxAttndingDoctor;
    private javax.swing.JComboBox<String> cboxDesiredRoom;
    private javax.swing.JComboBox<String> cboxIDAppment;
    private javax.swing.JTextField fielDateEstimated;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldAppmentDate;
    private javax.swing.JTextField fieldAppmentReason;
    private javax.swing.JTextField fieldBirthdate;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldFirstname;
    private javax.swing.JTextField fieldPassword;
    private javax.swing.JTextField fieldPasswordConfirm;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldUser;
    private javax.swing.JTextField labelLastname;
    private packagee.core.models.PanelRound panelUp;
    private javax.swing.JRadioButton rbtnDoctor;
    private javax.swing.JRadioButton rbtnSpecialty;
    private javax.swing.JTabbedPane tbbdPatientInfo;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtAppmentReason;
    private javax.swing.JLabel txtAppmentTime;
    private javax.swing.JLabel txtAppmentType;
    private javax.swing.JLabel txtBirthdate;
    private javax.swing.JLabel txtCancelAppment;
    private javax.swing.JLabel txtCancelObservations;
    private javax.swing.JLabel txtDateEstimated;
    private javax.swing.JLabel txtDesiredRoom;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFirstname;
    private javax.swing.JLabel txtGender;
    private javax.swing.JLabel txtHospitalReason;
    private javax.swing.JLabel txtIDAppment;
    private javax.swing.JLabel txtLastname;
    private javax.swing.JLabel txtObservations;
    private javax.swing.JLabel txtPassword;
    private javax.swing.JLabel txtPasswordConfirm;
    private javax.swing.JLabel txtPatientview;
    private javax.swing.JLabel txtPhone;
    private javax.swing.JLabel txtRequestMedical;
    private javax.swing.JLabel txtRquestHospital;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel txtappmentDate;
    private javax.swing.JLabel txtattdingDoctor;
    // End of variables declaration//GEN-END:variables
}
